# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170617_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
