# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170617_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='preview_image',
        ),
    ]
