# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.Channel'),
        ),
    ]
