# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcast_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
    ]
