# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_podcast_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='splash_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
