# Generated by Django 2.0.3 on 2018-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_splash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='splash_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
